spring:
  application:
    name: tc-f4-ms-customer

  datasource:
    hikari:
      pool-name: tc-f4-ms-customer
      maximum-pool-size: 5
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    url: jdbc:postgresql://localhost:5432/ms-customer
    driver-class-name: org.postgresql.Driver
    username: root
    password: secret
  cloud:
    function:
      web:
        path: /api
    config:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 90000
        loggerLevel: basic
  httpclient:
    disableSslValidation: true
    enabled: false
  okhttp:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}